# Generated by Django 5.0 on 2024-01-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('Accountid', models.IntegerField()),
                ('Categoryid', models.IntegerField()),
                ('Trans_type', models.CharField(max_length=50)),
                ('Payee', models.CharField(max_length=255)),
                ('Trans_to', models.CharField(max_length=255)),
            ],
        ),
    ]
