# Generated by Django 5.0 on 2024-01-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableintro',
            name='Payee_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
