# Generated by Django 5.0 on 2024-01-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_tableintro_payee_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableintro',
            name='Accountid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tableintro',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tableintro',
            name='Categoryid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tableintro',
            name='Payee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tableintro',
            name='Trans_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tableintro',
            name='Trans_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
