# Generated by Django 5.0 on 2024-01-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=5, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=8, null=True)),
                ('cpassword', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
