# Generated by Django 5.0 on 2024-01-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0004_alter_userinfo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('employee', 'emplyoee'), ('manager', 'manager'), ('other', 'other')], default='Student', max_length=255, null=True),
        ),
    ]
