# Generated by Django 5.0 on 2024-01-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0005_alter_userinfo_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
