# Generated by Django 5.0 on 2024-01-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0006_userinfo_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField(auto_now=True)),
                ('purchase_time', models.TimeField(auto_now=True)),
                ('amount_spent', models.PositiveIntegerField(blank=True, null=True)),
                ('bill_receipt', models.ImageField(upload_to='static/media/images')),
            ],
        ),
    ]
