# Generated by Django 5.0 on 2024-01-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0007_reportinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='purchase_time',
            field=models.TimeField(),
        ),
    ]
