# Generated by Django 5.0 on 2024-01-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0009_remove_reportinfo_purchase_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='category',
            field=models.CharField(blank=True, choices=[('Stationery', 'Stationery'), ('Technology', 'Technology'), ('Cosmetics', 'Cosmetics'), ('Groceries', 'Groceries'), ('Outfits', 'Outfits'), ('Other', 'Other')], default='Stationery', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
