# Generated by Django 5.0 on 2024-01-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0010_alter_reportinfo_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='number_of_products',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
