# Generated by Django 5.0 on 2024-01-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0011_reportinfo_number_of_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='bill_receipt',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
