# Generated by Django 5.0 on 2024-01-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0012_alter_reportinfo_bill_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='bill_receipt',
            field=models.ImageField(upload_to='D:/Abienv/FirstProject/media/'),
        ),
    ]
