# Generated by Django 5.0 on 2024-01-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0013_alter_reportinfo_bill_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='purchase_product',
            field=models.CharField(default='choose', max_length=255),
        ),
    ]
