# Generated by Django 5.0 on 2024-01-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0014_alter_reportinfo_purchase_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='amount_spent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
