# Generated by Django 5.0 on 2024-01-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0015_alter_reportinfo_amount_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='productinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_product', models.CharField(default='choose', max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('amount_spent', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('number_of_products', models.PositiveIntegerField(blank=True, null=True)),
                ('bill_receipt', models.ImageField(upload_to='D:/Abienv/FirstProject/media/')),
            ],
        ),
    ]
